# Generated by Django 3.2 on 2022-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=50)),
                ('badge_description', models.TextField(max_length=255)),
                ('badge_image', models.ImageField(blank=True, default='badges\\badge.jpg', upload_to='badges')),
                ('eligible_students', models.JSONField()),
            ],
        ),
    ]
