# Generated by Django 3.2 on 2022-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('badge_description', models.TextField(max_length=255)),
                ('badge_image', models.ImageField(blank=True, upload_to='badges')),
                ('email', models.TextField()),
            ],
        ),
    ]
