# Generated by Django 3.2 on 2022-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_image',
            field=models.ImageField(blank=True, upload_to='badges'),
        ),
    ]
