# Generated by Django 3.2 on 2022-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_badge_badge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='eligible_students',
            field=models.TextField(max_length=255),
        ),
    ]
